title: suivez le guide
author: le guide
favicon: "favicon.png"
goat_counter: "leguide"
theme_config:
  appearance: "auto"
  back_home_text: "â‡¤ home"
  
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-seo-tag
  
relative_links:
  enabled: true
  collections: true
  